### ISSUE TITLE
Very strange bug!

### ISSUE THREAD

**Issue by rananna** [OpenSourceEBike/TSDZ2_wireless#106]
@casainho , On the forum you asked me to change TSDZ2_FIRMWARE_MAJOR := 0
TSDZ2_FIRMWARE_MINOR := 6 in the makefile for the wireless controller
Previously, I had these set to 1 for both.
When I do this, the motor will not go out of initializing when I try to turn it on
When I set them to 1 everything is fine.
It is only a CFLAG, what is going on??

**Comment by rananna** [comment]
Could this be the source of the strange issues we are seeing on the forum?

**Comment by casainho** [comment]
I need to check when I am at the computer... Maybe just tomorrow.

**Comment by rananna** [comment]
On the forum I just confirmed a successful flash of the wireless remote.
The wireless controller still has issues, maybe it is somehow related to this?

**Comment by casainho** [comment]
APP_VER_MAJOR / MINOR and not TSDZ2_FIRMWARE_MAJOR / MINOR!!

Maybe the bootloader has some bug and needs increase of APP_VER_MAJOR / MINOR, that was some idea I had.

bl_settings:
	$(SREC_PATH)nrfutil settings generate --family NRF52840 --application $(OUTPUT_DIRECTORY)/TSDZ2_wireless.hex --application-version-string $(APP_VER_MAJOR).$(APP_VER_MINOR).0 --bootloader-version 1 --bl-settings-version 2 $(OUTPUT_DIRECTORY)/bl_settings.hex

OTA:
	$(SREC_PATH)nrfutil pkg generate --hw-version 52 --sd-req 0xB9 --application-version-string $(APP_VER_MAJOR).$(APP_VER_MINOR).0 --application $(OUTPUT_DIRECTORY)/TSDZ2_wireless.hex --key-file private.key --app-boot-validation VALIDATE_ECDSA_P256_SHA256 $(OUTPUT_DIRECTORY)/TSDZ2_wireless_ota_update.zip

**Comment by rananna** [comment]
What does tsdz2_firmware_major/minor do?

**Comment by rananna** [comment]
I will give him an updated file to try.

**Comment by casainho** [comment]
tsdz2_firmware_major/minor - at boot, display asks motor controller for his firmware version and checks against this, only initializes the motor / sends the configurations, if the version is correct, otherwise gives an error.

**Comment by rananna** [comment]
Checked bootloader code.app. version shouldn't cause any issue. Had user try  higher/lower version. Still an issue. 
He can flash wireless remote firmware, but not the controller.
Ran out of ideas.

**Comment by casainho** [comment]
I think you should focus on the next release for today and tomorrow - I can test it tomorrow. Then we will see as everyone of us will be using it.

**Comment by rananna** [comment]
Ok.
No more changes expected from me.
 I will test again today that I be sure everything works.

On the other topic found this on the Nordic site:
https://devzone.nordicsemi.com/f/nordic-q-a/58618/dfu-upgraded-app-wont-boot

We use -o0, maybe try -o3?

Of course, an important question to answer is  why are we not having the same issue?
