### ISSUE TITLE
Makefile can't cd to ./bootloader/firmware

### ISSUE THREAD

**Issue by casainho** [OpenSourceEBike/TSDZ2_wireless#27]
@rananna I am having the following issue when trying to build, can you please help?

mkdir _build
cd ./bootloader/firmware && make -f ./Makefile
nrfutil settings generate --family NRF52840 --application _build/TSDZ2_wireless.hex --application-version-string 0.5.0 --bootloader-version 1 --bl-settings-version 2 _build/bl_settings.hex 
/bin/sh: 1: cd: can't cd to ./bootloader/firmware

**Comment by casainho** [comment]
ok, I had to do this to get the bootloader repository:

git submodule update --init --recursive

**Comment by rananna** [comment]
@casainho, Ok, I didn't know how to fix the CI stuff. Where did you find this info?

**Comment by stsdc** [comment]
Remember to clone repo with its submodules:
`git clone --recursive git://github.com/foo/bar.git`
