### ISSUE TITLE
add travel range 

### ISSUE THREAD

**Issue by rananna** [OpenSourceEBike/TSDZ2_wireless#38]
Add ANT LEV travel range field.
This could be used as stated for travel range, or perhaps use it to display human power as this may be of more interest.

**Comment by casainho** [comment]
I would follow the standard and put there only the expected data.

Maybe we can implement fields for Garmin, that connect by Bluetooth to the wireless board and receive like motor power, battery SOC, motor temperature in ºC.

**Comment by rananna** [comment]
Done.
