### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by androslavic** [OpenSourceEBike/TSDZ2_wireless#52]
Hello,
I cannot access the documentation, when I click for any of documentation links(for example https://github.com/OpenSourceEBike/TSDZ2_wireless/blob/master/documentation/Overview.png) , I get 404 error.

**Comment by casainho** [comment]
Thanks. Yes, you must see here on the project page: https://opensourceebike.github.io/

I just updated that repo to link to this new page.
